name: Weekly Cherry Pick

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight
  workflow_dispatch:

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.REPO_BRANCH }}
      - name: Fetch from other repository
        run: |
          git fetch ${{ env.FETCH_REPO }} ${{ env.FETCH_BRANCH }}
      - name: Cherry pick missing commits
        run: |
          # Determine the last commit that was cherry-picked from FETCH_REPO
          last_commit=$(git rev-list --all --max-count=1)
          while [[ -z $last_commit ]]; do
            last_commit=$(git rev-list --all --max-count=1 --skip=1)
            if git branch -r --contains $last_commit | grep -q FETCH_HEAD; then
              break
            fi
            last_commit=""
          done
          # Get the list of missing commits
          missing_commits=$(git log $last_commit..FETCH_HEAD --pretty=format:"%H")
          # Cherry pick the missing commits
          git cherry-pick $missing_commits
          # Count the number of cherry-picked commits
          num_commits=$(echo $missing_commits | wc -w)
          echo "NUM_COMMITS=$num_commits" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Cherry Pick $(date +'%Y-%m-%d') (${{ env.NUM_COMMITS }} commits)"
