name: Cherry-pick commits
on:
  workflow_dispatch:

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Git user info
        run: |
          git config --global user.name ${{github.actor}}
          git config --global user.email ${{github.actor}}@users.noreply.github.com

      - name: Fetch repository
        run: |
          echo "Fetching repository ${{ env.FETCH_REPO }} branch ${{ env.FETCH_BRANCH }}"
          git fetch https://github.com/mt6768-dev/android_device_xiaomi_lancelot lineage-20

      - name: Find last cherry-picked commit
        id: last_cherry_pick
        run: |
          wget -O get_commits.py https://gist.githubusercontent.com/marat2509/c4b824eac3b8efbb4cad6d0b67dcf305/raw/get_cherrypicked.py
          LAST_CHERRY_PICKED_COMMIT=$(python3 get_commits.py)
          echo "Last cherry-picked commit: $LAST_CHERRY_PICKED_COMMIT"
          echo "LAST_CHERRY_PICKED_COMMIT=$LAST_CHERRY_PICKED_COMMIT" >> $GITHUB_ENV

      - name: Get missing commits
        id: missing_commits
        run: |
          echo "Getting missing commits"
          MISSING_COMMITS=$(git log --pretty=format:"%H" $LAST_CHERRY_PICKED_COMMIT..FETCH_HEAD)
          echo "Missing commits: $MISSING_COMMITS"
          
          echo "MISSING_COMMITS<<EOF" >> $GITHUB_ENV
          echo $MISSING_COMMITS >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Cherry-pick missing commits
        run: |
          echo "Cherry-picking missing commits"
          for commit in $MISSING_COMMITS; do
            if ! git cherry-pick $commit; then
              echo "Conflict with commit $commit"
              git cherry-pick --abort
            fi
          done

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: main
          destination_branch: main
          pr_title: "Cherry-picked commits from ${{ env.FETCH_REPO }}:${{ env.FETCH_BRANCH }}